modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="cutemobs"
version="1.0.0"
displayName="Cute Mobs"
description='''Criaturas supermonas: Mochi, Nube y Brote.'''

[[dependencies.cutemobs]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.cutemobs]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
